
all: ex1 ex2 ex4 ex5

ex1: ex1.md
	pandoc -s --mathjax ex1.md -o ex1.pdf

ex2: ex2.md
	pandoc -s --mathjax ex2.md -o ex2.pdf

ex4: ex4.md
	pandoc -s --mathjax ex4.md -o ex4.pdf

ex3: ex5.md
	pandoc -s --mathjax ex5.md -o ex5.pdf