
all: ex2 ex3 ex4

ex1: ex1.md
	pandoc -s --mathjax ex1.md -o ex1.pdf

ex2: ex2.md
	pandoc -s --mathjax ex2.md -o ex2.pdf

ex3: ex3.md
	pandoc -s --mathjax ex3.md -o ex3.pdf

ex4: ex4.md
	pandoc -s --mathjax ex4.md -o ex4.pdf
